/* NetScript browser bundle — generated by scripts/build-editor.mjs. Do not edit by hand. */
(function () {
"use strict";

// ---- model.ts ----
/**
 * NetScript model — the source of truth.
 *
 * A NetModel is a declarative, layout-free description of devices, the ports
 * between them, and the links that connect them. Positions are assigned later
 * by the layout pass; renderers are pure views over the positioned model.
 *
 * v0.1 is physical-layer only (devices · ports · cabling). Logical overlays
 * (VLAN / subnet / bond semantics) and importers (UniFi / Proxmox / SysML v2)
 * are post-0.1 — see README roadmap.
 */

                  
                                              
                                            

/** Vertical tier — drives layout and link-class inference. */
const byId = (m          )                      =>
  new Map(m.devices.map((d) => [d.id, d]));

// boundary anchors on a positioned device
const top    = (d        )     => ({ x: d.x , y: d.y  - d.h  / 2 });
const bottom = (d        )     => ({ x: d.x , y: d.y  + d.h  / 2 });
const leftP  = (d        )     => ({ x: d.x  - d.w  / 2, y: d.y  });
const rightP = (d        )     => ({ x: d.x  + d.w  / 2, y: d.y  });
const escapeXml = (s        )         =>
  String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;")
           .replace(/>/g, "&gt;").replace(/"/g, "&quot;");


const esc = escapeXml;

// ---- themes.ts ----
/** NetScript themes — palette/typography tokens. Same model, swappable view. */
                                        

                        
               
               
               
             
                      
                 
                   
                     
                      
                 
                  
                                                             
               
              
                                                                           
          
               
                
                 
                   
                                    
          
                
                   
                     
                    
          
                   
                     
                   
                      
 

const SANS = "Inter, system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif";
const MONO = "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace";
const clean        = {
  name: "clean", font: SANS, mono: MONO, bg: "#ffffff", grid: null,
  cardFill: "#ffffff", cardStroke: "#d7dbe2", cardStrokeW: 1.2, radius: 8, shadow: true,
  chipStroke: null, text: "#1f2430", sub: "#6b7280", showMgmt: false,
  link: "#7c8696", linkW: 1.5, jumps: true, endDots: true,
  speedColor: { WAN: "#64748b", "1G": "#94a3b8", "10G": "#3b82f6", "25G": "#ef6c2f", "40G": "#d97706", "100G": "#db2777", LAG: "#7c3aed" },
  pill: true, pillFill: "#ffffff", pillStroke: "#e5e7eb", speedText: "#475569",
  zoneFill: "#f8fafc", zoneStroke: "#e2e8f0", zoneText: "#64748b", titleBlock: false,
};
const blueprint        = {
  name: "blueprint", font: MONO, mono: MONO, bg: "#0c356a", grid: "#1c4a8a",
  cardFill: "none", cardStroke: "#bcd6ff", cardStrokeW: 1.2, radius: 4, shadow: false,
  chipStroke: "#bcd6ff", text: "#eaf2ff", sub: "#9dc0f0", showMgmt: true,
  link: "#cfe0ff", linkW: 1.3, jumps: true, endDots: true,
  speedColor: { WAN: "#cfe0ff", "1G": "#9dc0f0", "10G": "#7fd1ff", "25G": "#ffd27f", "40G": "#ffc04d", "100G": "#ff9ed6", LAG: "#a7f3d0" },
  pill: false, pillFill: "none", pillStroke: "none", speedText: "#dbe9ff",
  zoneFill: "#0e3f7d", zoneStroke: "#2f63a8", zoneText: "#bcd6ff", titleBlock: true,
};
const THEMES                        = { clean, blueprint };
const resolveTheme = (name        )        => THEMES[name] ?? clean;


// ---- glyphs.ts ----
/** Vendor-neutral device glyphs. Each returns an SVG fragment string. */
                                       

                                                                                                   

const router          = (cx, cy, s, st, fill, sw) => {
  const r = s * 0.5;
  let out = `<circle cx="${cx}" cy="${cy}" r="${r.toFixed(1)}" fill="${fill}" stroke="${st}" stroke-width="${sw}"/>`;
  const a = s * 0.3;
  for (const [tx, ty, dxn, dyn] of [[-a,0,1,0],[a,0,-1,0],[0,-a,0,1],[0,a,0,-1]]         ) {
    const x = cx + tx, y = cy + ty, hb = s * 0.12;
    out += `<line x1="${(cx+tx*0.2).toFixed(1)}" y1="${(cy+ty*0.2).toFixed(1)}" x2="${x.toFixed(1)}" y2="${y.toFixed(1)}" stroke="${st}" stroke-width="${sw}"/>`;
    out += `<path d="M ${x.toFixed(1)},${y.toFixed(1)} l ${(-dxn*hb - dyn*hb*0.7).toFixed(1)},${(-dyn*hb - dxn*hb*0.7).toFixed(1)} M ${x.toFixed(1)},${y.toFixed(1)} l ${(-dxn*hb + dyn*hb*0.7).toFixed(1)},${(-dyn*hb + dxn*hb*0.7).toFixed(1)}" stroke="${st}" stroke-width="${sw}" fill="none"/>`;
  }
  return out;
};

const sw_switch          = (cx, cy, s, st, fill, sw) => {
  const w = s * 1.25, h = s * 0.62;
  let out = `<rect x="${(cx-w/2).toFixed(1)}" y="${(cy-h/2).toFixed(1)}" width="${w.toFixed(1)}" height="${h.toFixed(1)}" rx="3" fill="${fill}" stroke="${st}" stroke-width="${sw}"/>`;
  for (const [yy, dirn] of [[-h*0.22,1],[h*0.22,-1]]         ) {
    const y = cy + yy;
    out += `<line x1="${(cx-w*0.32).toFixed(1)}" y1="${y.toFixed(1)}" x2="${(cx+w*0.32).toFixed(1)}" y2="${y.toFixed(1)}" stroke="${st}" stroke-width="${sw}"/>`;
    const tipx = cx + dirn * w * 0.32;
    out += `<path d="M ${tipx.toFixed(1)},${y.toFixed(1)} l ${(-dirn*s*0.13).toFixed(1)},${(-s*0.09).toFixed(1)} M ${tipx.toFixed(1)},${y.toFixed(1)} l ${(-dirn*s*0.13).toFixed(1)},${(s*0.09).toFixed(1)}" stroke="${st}" stroke-width="${sw}" fill="none"/>`;
  }
  return out;
};

const server          = (cx, cy, s, st, fill, sw) => {
  const w = s * 0.78, h = s * 1.05;
  let out = `<rect x="${(cx-w/2).toFixed(1)}" y="${(cy-h/2).toFixed(1)}" width="${w.toFixed(1)}" height="${h.toFixed(1)}" rx="3" fill="${fill}" stroke="${st}" stroke-width="${sw}"/>`;
  for (const k of [-1,0,1]) {
    const y = cy + k * h * 0.26;
    out += `<line x1="${(cx-w*0.32).toFixed(1)}" y1="${y.toFixed(1)}" x2="${(cx+w*0.18).toFixed(1)}" y2="${y.toFixed(1)}" stroke="${st}" stroke-width="${sw}"/>`;
    out += `<circle cx="${(cx+w*0.30).toFixed(1)}" cy="${y.toFixed(1)}" r="${Math.max(1.2,sw).toFixed(1)}" fill="${st}"/>`;
  }
  return out;
};

const storage          = (cx, cy, s, st, fill, sw) => {
  const w = s * 1.0, rh = s * 0.26; let out = "";
  for (const k of [-1,0,1]) {
    const y = cy + k * (rh + 2);
    out += `<rect x="${(cx-w/2).toFixed(1)}" y="${(y-rh/2).toFixed(1)}" width="${w.toFixed(1)}" height="${rh.toFixed(1)}" rx="3" fill="${fill}" stroke="${st}" stroke-width="${sw}"/>`;
    out += `<circle cx="${(cx+w*0.34).toFixed(1)}" cy="${y.toFixed(1)}" r="${Math.max(1.2,sw).toFixed(1)}" fill="${st}"/>`;
  }
  return out;
};

const firewall          = (cx, cy, s, st, fill, sw) => {
  const w = s * 1.2, h = s * 0.9;
  let out = `<rect x="${(cx-w/2).toFixed(1)}" y="${(cy-h/2).toFixed(1)}" width="${w.toFixed(1)}" height="${h.toFixed(1)}" rx="2" fill="${fill}" stroke="${st}" stroke-width="${sw}"/>`;
  // brick courses
  out += `<line x1="${(cx-w/2).toFixed(1)}" y1="${cy.toFixed(1)}" x2="${(cx+w/2).toFixed(1)}" y2="${cy.toFixed(1)}" stroke="${st}" stroke-width="${sw}"/>`;
  out += `<line x1="${cx.toFixed(1)}" y1="${(cy-h/2).toFixed(1)}" x2="${cx.toFixed(1)}" y2="${cy.toFixed(1)}" stroke="${st}" stroke-width="${sw}"/>`;
  out += `<line x1="${(cx-w*0.25).toFixed(1)}" y1="${cy.toFixed(1)}" x2="${(cx-w*0.25).toFixed(1)}" y2="${(cy+h/2).toFixed(1)}" stroke="${st}" stroke-width="${sw}"/>`;
  out += `<line x1="${(cx+w*0.25).toFixed(1)}" y1="${cy.toFixed(1)}" x2="${(cx+w*0.25).toFixed(1)}" y2="${(cy+h/2).toFixed(1)}" stroke="${st}" stroke-width="${sw}"/>`;
  return out;
};

const ap          = (cx, cy, s, st, fill, sw) => {
  const bw = s * 0.9, bh = s * 0.4, by = cy + s * 0.45;
  let out = `<rect x="${(cx-bw/2).toFixed(1)}" y="${(by-bh/2).toFixed(1)}" width="${bw.toFixed(1)}" height="${bh.toFixed(1)}" rx="3" fill="${fill}" stroke="${st}" stroke-width="${sw}"/>`;
  for (const i of [1,2,3]) {
    const rr = s * 0.22 * i;
    out += `<path d="M ${(cx-rr).toFixed(1)},${(by-bh*0.6).toFixed(1)} A ${rr.toFixed(1)},${rr.toFixed(1)} 0 0 1 ${(cx+rr).toFixed(1)},${(by-bh*0.6).toFixed(1)}" fill="none" stroke="${st}" stroke-width="${sw}"/>`;
  }
  return out;
};

const desktop          = (cx, cy, s, st, fill, sw) => {
  const w = s * 1.15, h = s * 0.78;
  let out = `<rect x="${(cx-w/2).toFixed(1)}" y="${(cy-h/2-s*0.1).toFixed(1)}" width="${w.toFixed(1)}" height="${h.toFixed(1)}" rx="3" fill="${fill}" stroke="${st}" stroke-width="${sw}"/>`;
  out += `<line x1="${cx.toFixed(1)}" y1="${(cy+h/2-s*0.1).toFixed(1)}" x2="${cx.toFixed(1)}" y2="${(cy+h/2+s*0.12).toFixed(1)}" stroke="${st}" stroke-width="${sw}"/>`;
  out += `<line x1="${(cx-w*0.25).toFixed(1)}" y1="${(cy+h/2+s*0.12).toFixed(1)}" x2="${(cx+w*0.25).toFixed(1)}" y2="${(cy+h/2+s*0.12).toFixed(1)}" stroke="${st}" stroke-width="${sw}"/>`;
  return out;
};

const CLOUD = "M54,40 H14 C6.3,40 0,33.7 0,26 0,18.8 5.4,12.9 12.4,12.1 14.7,5.1 21.3,0 29,0 c8,0 14.7,5.5 16.6,12.9 C53.4,13.6 64,18.3 64,26 64,33.7 60.6,40 54,40 Z";
const cloud          = (cx, cy, s, st, fill, sw) => {
  const scale = (s * 1.6) / 64, tx = cx - 32 * scale, ty = cy - 20 * scale;
  return `<g transform="translate(${tx.toFixed(1)},${ty.toFixed(1)}) scale(${scale.toFixed(3)})"><path d="${CLOUD}" fill="${fill}" stroke="${st}" stroke-width="${(sw/scale).toFixed(2)}"/></g>`;
};
const GLYPH                        = {
  cloud, router, firewall, switch: sw_switch, server, storage, ap, desktop,
};
const KIND_COLOR                       = {
  cloud: "#64748b", router: "#2563eb", firewall: "#b91c1c", switch: "#0d9488",
  server: "#4f46e5", storage: "#7c3aed", ap: "#ea580c", desktop: "#475569",
};


// ---- layout.ts ----
/**
 * NetScript layout — assigns x/y/w/h to a declarative model and derives zone
 * boxes. v0.1 is a deterministic tiered/rack layout (edge → core pair → rack
 * columns with a ToR over staggered hosts). A real crossing-minimising layered
 * placer is roadmap.
 */
                                                   

const SIZE                                   = {
  wan: [120, 46], edge: [150, 54], core: [150, 52], tor: [150, 50], host: [104, 48],
};
const LEFT = 92, RIGHT = 92, ZW = 356, GAP = 116;
const Y = { wan: 44, edge: 150, core: 278, tor: 430, host0: 560, hostStep: 118 };
const ROW_EVEN = [-114, 38], ROW_ODD = [-38, 114];   // staggered host x-offsets
function layoutModel(m          )         {
  const n = m.racks.length;
  const W = LEFT + n * ZW + (n - 1) * GAP + RIGHT;
  const cx0 = W / 2;
  const rackCenter                         = {};
  m.racks.forEach((r, i) => { rackCenter[r.id] = LEFT + ZW / 2 + i * (ZW + GAP); });

  for (const d of m.devices) [d.w, d.h] = SIZE[d.tier];

  for (const d of m.devices) {
    if (d.tier === "wan") { d.x = cx0; d.y = Y.wan; }
    else if (d.tier === "edge") { d.x = cx0; d.y = Y.edge; }
  }
  const cores = m.devices.filter((d) => d.tier === "core");
  const cgap = 240;
  cores.forEach((d, i) => { d.x = cx0 - (cores.length - 1) * cgap / 2 + i * cgap; d.y = Y.core; });

  for (const r of m.racks) {
    const cx = rackCenter[r.id];
    const tor = m.devices.find((d) => d.tier === "tor" && d.rack === r.id);
    if (tor) { tor.x = cx; tor.y = Y.tor; }
    const hosts = m.devices.filter((d) => d.tier === "host" && d.rack === r.id);
    hosts.forEach((d, i) => {
      const row = Math.floor(i / 2), col = i % 2;
      d.x = cx + (row % 2 === 0 ? ROW_EVEN : ROW_ODD)[col];
      d.y = Y.host0 + row * Y.hostStep;
    });
  }

  const pad = { l: 38, r: 38, t: 20, b: 24 };
  const bbox = (ds          ) => {
    const x1 = Math.min(...ds.map((d) => d.x  - d.w  / 2)), x2 = Math.max(...ds.map((d) => d.x  + d.w  / 2));
    const y1 = Math.min(...ds.map((d) => d.y  - d.h  / 2)), y2 = Math.max(...ds.map((d) => d.y  + d.h  / 2));
    return { x: x1, y: y1, w: x2 - x1, h: y2 - y1 };
  };
  const zones         = [];
  if (cores.length) { const b = bbox(cores); zones.push({ x: b.x - pad.l, y: b.y - pad.t, w: b.w + pad.l + pad.r, h: b.h + pad.t + pad.b, label: "CORE" }); }
  for (const r of m.racks) {
    const ds = m.devices.filter((d) => d.rack === r.id);
    if (!ds.length) continue;
    const b = bbox(ds);
    zones.push({ x: b.x - pad.l, y: b.y - pad.t, w: b.w + pad.l + pad.r, h: b.h + pad.t + pad.b, label: `${r.label} · ${r.role}`.toUpperCase() });
  }

  const maxY = Math.max(...m.devices.map((d) => d.y  + d.h  / 2));
  return { W, H: maxY + 110, zones };
}


// ---- router.ts ----
/**
 * NetScript router — orthogonal cabling with:
 *   - per-tier horizontal LANE allocation (greedy interval colouring),
 *   - vertical uplink RISERS with core-side port fan-out,
 *   - per-rack local lanes for intra-rack links,
 *   - line-jumps only on genuinely unavoidable crossings.
 *
 * This is the workable skeleton of NetScript's eventual layered, port-aware
 * router. It is NOT yet crossing-minimising (no node/lane reordering) — see
 * README roadmap.
 */
function allocLanes(
  runs                                           , y0        , gap        , margin = 12,
)                         {
  const slots                       = [];
  const ys                         = {};
  for (const r of [...runs].sort((a, b) => Math.abs(b.x2 - b.x1) - Math.abs(a.x2 - a.x1))) {
    const xlo = Math.min(r.x1, r.x2), xhi = Math.max(r.x1, r.x2);
    let placed = false;
    for (let i = 0; i < slots.length; i++) {
      if (slots[i].every(([a, b]) => xhi + margin < a || xlo - margin > b)) {
        slots[i].push([xlo, xhi]); ys[r.key] = y0 + i * gap; placed = true; break;
      }
    }
    if (!placed) { ys[r.key] = y0 + slots.length * gap; slots.push([[xlo, xhi]]); }
  }
  return ys;
}
function classify(m          )       {
  const id = new Map(m.devices.map((d) => [d.id, d]));
  for (const l of m.links) {
    const ta = id.get(l.a) .tier, tb = id.get(l.b) .tier;
    const s = new Set([ta, tb]);
    if (s.has("wan")) l.klass = "wan";
    else if (s.has("edge") && s.has("core")) l.klass = "e2c";
    else if (ta === "core" && tb === "core") l.klass = "peer";
    else if (s.has("tor") && s.has("core")) l.klass = "uplink";
    else l.klass = "intra";
  }
}
function buildRoutes(m          )         {
  classify(m);
  const id = new Map(m.devices.map((d) => [d.id, d]));
  const D = (x        ) => id.get(x) ;
  const cores = m.devices.filter((d) => d.tier === "core").sort((p, q) => p.x  - q.x );
  const core = cores[0], tor = m.devices.find((d) => d.tier === "tor") , edge = m.devices.find((d) => d.tier === "edge") ;
  const coreBottom = core.y  + core.h  / 2, torBottom = tor.y  + tor.h  / 2, edgeBottom = edge.y  + edge.h  / 2;
  const rackOrder = m.racks.map((r) => r.id);

  const e2c = m.links.filter((l) => l.klass === "e2c");
  const e2cLanes = allocLanes(e2c.map((l, i) => ({ key: String(i), x1: D(l.a).x , x2: D(l.b).x  })), edgeBottom + 23, 13);

  const ups = m.links.filter((l) => l.klass === "uplink");
  const torOf = (l      ) => (D(l.a).tier === "tor" ? D(l.a) : D(l.b));
  const coreOf = (l      ) => (D(l.a).tier === "core" ? D(l.a) : D(l.b));
  const upLanes = allocLanes(
    ups.map((l, i) => ({ key: String(i), x1: torOf(l).x , x2: coreOf(l).x  + (rackOrder.indexOf(torOf(l).rack ) - 1) * 42 })),
    coreBottom + 18, 12,
  );

  const routes         = [];
  m.links.forEach((l, idx) => {
    const a = D(l.a), b = D(l.b);
    if (l.klass === "wan") {
      const lo = a.tier === "wan" ? b : a, hi = a.tier === "wan" ? a : b;
      routes[idx] = [top(lo), bottom(hi)];
    } else if (l.klass === "peer") {
      const lft = a.x  < b.x  ? a : b, rgt = a.x  < b.x  ? b : a;
      routes[idx] = [rightP(lft), leftP(rgt)];
    } else if (l.klass === "e2c") {
      const lo = a.tier === "edge" ? a : b, hi = a.tier === "edge" ? b : a;
      const A = bottom(lo), B = top(hi), ly = e2cLanes[String(e2c.indexOf(l))];
      routes[idx] = [A, { x: A.x, y: ly }, { x: B.x, y: ly }, B];
    } else if (l.klass === "uplink") {
      const t = torOf(l), c = coreOf(l), ci = cores.indexOf(c);
      const A = top(t), ax = A.x + (ci === 0 ? -7 : 7);
      const bx = c.x  + (rackOrder.indexOf(t.rack ) - 1) * 42, by = bottom(c).y;
      const ly = upLanes[String(ups.indexOf(l))];
      routes[idx] = [{ x: ax, y: A.y }, { x: ax, y: ly }, { x: bx, y: ly }, { x: bx, y: by }];
    } else { // intra
      const t = a.tier === "tor" ? a : b, h = a.tier === "tor" ? b : a;
      const A = bottom(t), B = top(h);
      const hosts = m.devices.filter((d) => d.rack === t.rack && d.tier === "host");
      const lanes = allocLanes(hosts.map((hh) => ({ key: hh.id, x1: t.x , x2: hh.x  })), torBottom + 23, 11);
      const ly = lanes[h.id];
      const ax = A.x + Math.max(-55, Math.min(55, (B.x - A.x) * 0.5));
      routes[idx] = [{ x: ax, y: A.y }, { x: ax, y: ly }, { x: B.x, y: ly }, B];
    }
  });
  return routes;
}
const segments = (pts      )        => {
  const out        = [];
  for (let i = 0; i < pts.length - 1; i++) {
    const p = pts[i], q = pts[i + 1];
    out.push({ x1: p.x, y1: p.y, x2: q.x, y2: q.y, o: Math.abs(p.y - q.y) < 0.5 ? "h" : "v" });
  }
  return out;
};
function offsetPts(pts      , d        )       {
  const segs = segments(pts).map((s) => s.o === "v"
    ? { ...s, x1: s.x1 + d, x2: s.x2 + d }
    : { ...s, y1: s.y1 + d, y2: s.y2 + d });
  const out       = [{ x: segs[0].x1, y: segs[0].y1 }];
  for (const s of segs) out.push({ x: s.x2, y: s.y2 });
  return out;
}

function jumpsOnH(h     , foreignV       , r        )           {
  const y = h.y1, lo = Math.min(h.x1, h.x2), hi = Math.max(h.x1, h.x2), xs           = [];
  for (const v of foreignV) {
    const vx = v.x1, vlo = Math.min(v.y1, v.y2), vhi = Math.max(v.y1, v.y2);
    if (lo + 4 < vx && vx < hi - 4 && vlo + 1 < y && y < vhi - 1) xs.push(vx);
  }
  return [...new Set(xs)].sort((a, b) => a - b);
}
function pathD(pts      , myIdx        , allSegs         , jumps = true, r = 5)         {
  const segs = segments(pts);
  let foreignV        = [];
  if (jumps) allSegs.forEach((ss, j) => { if (j !== myIdx) foreignV = foreignV.concat(ss.filter((s) => s.o === "v")); });
  let d = `M ${segs[0].x1.toFixed(1)},${segs[0].y1.toFixed(1)} `;
  for (const s of segs) {
    if (s.o === "v" || !jumps) { d += `L ${s.x2.toFixed(1)},${s.y2.toFixed(1)} `; continue; }
    const y = s.y1, l2r = s.x2 >= s.x1;
    let jx = jumpsOnH(s, foreignV, r); if (!l2r) jx = jx.reverse();
    for (const x of jx) {
      const sweep = l2r ? 1 : 0;
      d += `L ${(x - r).toFixed(1)},${y.toFixed(1)} A ${r},${r} 0 0 ${sweep} ${(x + r).toFixed(1)},${y.toFixed(1)} `;
    }
    d += `L ${s.x2.toFixed(1)},${s.y2.toFixed(1)} `;
  }
  return d.trim();
}


// ---- parser.ts ----
/**
 * NetScript `.net` parser — text DSL → NetModel.
 *
 * Grammar (physical layer, v0.1):
 *
 *   ---                         # optional frontmatter
 *   title: My Lab
 *   theme: blueprint
 *   ---
 *
 *   <id> <kind> "label" [tier <tier>] [mgmt <addr>]      # device
 *   rack <id> "role" { ... }                             # group (members default tier host)
 *   <a> -> <b> : <speed> [lag]                           # link (-- = peer; class inferred)
 *
 *   # line comments with '#'
 *
 * Link class (uplink / peer / intra / e2c / wan) is inferred from tiers by the
 * router, so authors never hand-classify. `tier` is optional where it can be
 * inferred from kind (cloud→wan, firewall/router→edge, host kinds→host, a
 * switch→core at top level / tor inside a rack).
 */
                                                                            

const KINDS = new Set        (["cloud", "router", "firewall", "switch", "server", "storage", "ap", "desktop"]);
const TIERS = new Set        (["wan", "edge", "core", "tor", "host"]);
const SPEEDS = new Set        (["WAN", "1G", "10G", "25G", "40G", "100G", "LAG"]);

function inferTier(kind      , inRack         )       {
  if (kind === "cloud") return "wan";
  if (kind === "firewall" || kind === "router") return "edge";
  if (kind === "switch") return inRack ? "tor" : "core";
  return "host"; // server / storage / ap / desktop
}

/** Strip an unquoted `#` comment from a line. */
function stripComment(line        )         {
  let q = false;
  for (let i = 0; i < line.length; i++) {
    const c = line[i];
    if (c === '"') q = !q;
    else if (c === "#" && !q) return line.slice(0, i);
  }
  return line;
}
function parseNet(src        )           {
  const lines = src.split(/\r?\n/);
  const model           = { title: "Untitled", devices: [], links: [], racks: [] };
  let i = 0;

  // ---- frontmatter ----
  if (lines[0] !== undefined && lines[0].trim() === "---") {
    i = 1;
    for (; i < lines.length && lines[i].trim() !== "---"; i++) {
      const m = lines[i].match(/^\s*([\w-]+)\s*:\s*(.*)$/);
      if (!m) continue;
      const key = m[1].toLowerCase(), val = m[2].trim();
      if (key === "title") model.title = val;
      else if (key === "theme") model.theme = val;
    }
    i++; // consume closing ---
  }

  // ---- body ----
  let rack                = null;
  for (; i < lines.length; i++) {
    const ln = i + 1;
    const t = stripComment(lines[i]).trim();
    if (!t) continue;

    if (t === "}") { rack = null; continue; }

    // rack <id> "role" {
    let m = t.match(/^rack\s+(\S+)\s+"([^"]*)"\s*\{$/);
    if (m) {
      const id = m[1];
      if (model.racks.some((r) => r.id === id)) throw new Error(`line ${ln}: duplicate rack "${id}"`);
      model.racks.push({ id, label: `Rack ${id}`, role: m[2] });
      rack = id;
      continue;
    }

    // <a> (->|--) <b> : <speed> [lag]
    m = t.match(/^(\S+)\s*(->|--)\s*(\S+)\s*:\s*([A-Za-z0-9]+)(\s+lag)?$/i);
    if (m) {
      const speed = m[4].toUpperCase();
      if (!SPEEDS.has(speed)) throw new Error(`line ${ln}: unknown speed "${m[4]}"`);
      model.links.push({ a: m[1], b: m[3], speed: speed         , ...(m[5] ? { bond: true } : {}) });
      continue;
    }

    // <id> <kind> "label" [tier X] [mgmt Y]
    m = t.match(/^(\S+)\s+(\S+)\s+"([^"]*)"\s*(.*)$/);
    if (m) {
      const id = m[1], kindRaw = m[2].toLowerCase(), label = m[3], rest = m[4];
      if (model.devices.some((d) => d.id === id)) throw new Error(`line ${ln}: duplicate device id "${id}"`);
      if (!KINDS.has(kindRaw)) throw new Error(`line ${ln}: unknown kind "${m[2]}"`);
      const kind = kindRaw        ;
      const dev         = { id, kind, label, tier: "host" };
      const tm = rest.match(/\btier\s+(\S+)/);
      if (tm) {
        if (!TIERS.has(tm[1])) throw new Error(`line ${ln}: unknown tier "${tm[1]}"`);
        dev.tier = tm[1]        ;
      } else {
        dev.tier = inferTier(kind, rack !== null);
      }
      const mm = rest.match(/\bmgmt\s+(\S+)/);
      if (mm) dev.mgmt = mm[1];
      if (rack !== null) dev.rack = rack;
      model.devices.push(dev);
      continue;
    }

    throw new Error(`line ${ln}: cannot parse → ${t}`);
  }

  // ---- light validation (resolvable endpoints) ----
  const ids = new Set(model.devices.map((d) => d.id));
  for (const l of model.links) {
    if (!ids.has(l.a)) throw new Error(`link references unknown device "${l.a}"`);
    if (!ids.has(l.b)) throw new Error(`link references unknown device "${l.b}"`);
  }
  return model;
}


// ---- render.ts ----
/** NetScript renderer — positioned model + theme → SVG string. */
                                                        
                                         

const SPEED_ORDER          = ["1G", "10G", "25G", "40G", "100G", "LAG"];
function renderModel(m          , themeName                 = "clean")         {
  const S = typeof themeName === "string" ? resolveTheme(themeName) : themeName;
  const { W, H, zones } = layoutModel(m);
  const id = new Map(m.devices.map((d) => [d.id, d]));
  const routes = buildRoutes(m);
  const allSegs = routes.map((p) => segments(p));
  const out           = [`<svg viewBox="0 0 ${W} ${H}" xmlns="http://www.w3.org/2000/svg" font-family="${S.font}">`];

  if (S.shadow)
    out.push('<defs><filter id="sh" x="-20%" y="-20%" width="140%" height="140%"><feDropShadow dx="0" dy="1.5" stdDeviation="2.2" flood-color="#0f172a" flood-opacity="0.16"/></filter></defs>');
  out.push(`<rect width="${W}" height="${H}" fill="${S.bg}"/>`);
  if (S.grid)
    out.push(`<defs><pattern id="grd" width="28" height="28" patternUnits="userSpaceOnUse"><path d="M28 0H0V28" fill="none" stroke="${S.grid}" stroke-width="1"/></pattern></defs><rect width="${W}" height="${H}" fill="url(#grd)"/>`);

  // zones
  for (const z of zones) {
    out.push(`<rect x="${z.x.toFixed(1)}" y="${z.y.toFixed(1)}" width="${z.w.toFixed(1)}" height="${z.h.toFixed(1)}" rx="13" fill="${S.zoneFill}" stroke="${S.zoneStroke}" stroke-width="1.2"/>`);
    out.push(`<text x="${(z.x + 6).toFixed(1)}" y="${(z.y - 7).toFixed(1)}" font-size="11.5" fill="${S.zoneText}" font-weight="700" letter-spacing="1.8" font-family="${S.mono}">${esc(z.label)}</text>`);
  }

  // links
  m.links.forEach((l, i) => {
    const col = S.speedColor[l.speed] ?? S.link;
    const lw = S.linkW * (l.speed === "100G" ? 1.7 : 1);
    if (l.bond) {
      for (const off of [-2.4, 2.4])
        out.push(`<path d="${pathD(offsetPts(routes[i], off), i, allSegs, S.jumps)}" fill="none" stroke="${col}" stroke-width="${S.linkW}" stroke-linecap="round" stroke-linejoin="round"/>`);
    } else {
      out.push(`<path d="${pathD(routes[i], i, allSegs, S.jumps)}" fill="none" stroke="${col}" stroke-width="${lw.toFixed(1)}" stroke-linecap="round" stroke-linejoin="round"/>`);
    }
    if (S.endDots) for (const e of [routes[i][0], routes[i][routes[i].length - 1]])
      out.push(`<circle cx="${e.x.toFixed(1)}" cy="${e.y.toFixed(1)}" r="2.3" fill="${col}"/>`);
  });

  // speed pills (trunk links + LAG tags) — intra-rack speed is carried by colour + legend
  const pill = (mx        , my        , label        , col        ) => {
    const tw = 7.0 * label.length + 12;
    if (S.pill) out.push(`<rect x="${(mx - tw / 2).toFixed(1)}" y="${(my - 9).toFixed(1)}" width="${tw.toFixed(1)}" height="16" rx="8" fill="${S.pillFill}" stroke="${S.pillStroke}" stroke-width="1"/>`);
    out.push(`<text x="${mx.toFixed(1)}" y="${(my + 2).toFixed(1)}" font-size="10" text-anchor="middle" fill="${S.speedText || col}" font-weight="600" font-family="${S.mono}">${esc(label)}</text>`);
  };
  m.links.forEach((l, i) => {
    const col = S.speedColor[l.speed] ?? S.link, pts = routes[i];
    if (l.klass === "e2c") { const p = pts[pts.length - 2], q = pts[pts.length - 1]; pill(q.x, (p.y + q.y) / 2, l.speed, col); }
    else if (l.klass === "peer") { const p = pts[0], q = pts[1]; pill((p.x + q.x) / 2, p.y, "100G", col); }
    else if (l.klass === "wan") { const p = pts[0], q = pts[1]; pill((p.x + q.x) / 2, (p.y + q.y) / 2, "WAN", col); }
    if (l.bond) { const p = pts[pts.length - 2], q = pts[pts.length - 1]; pill(q.x, (p.y + q.y) / 2 + 14, "LAG", S.speedColor.LAG); }
  });

  // nodes
  for (const d of m.devices) {
    const cx = d.x , cy = d.y , w = d.w , h = d.h , kc = KIND_COLOR[d.kind];
    const filt = S.shadow ? ' filter="url(#sh)"' : "";
    out.push(`<rect x="${(cx - w / 2).toFixed(1)}" y="${(cy - h / 2).toFixed(1)}" width="${w}" height="${h}" rx="${S.radius}" fill="${S.cardFill}" stroke="${S.cardStroke}" stroke-width="${S.cardStrokeW}"${filt}/>`);
    const gx = cx - w / 2 + 19;
    const hasMgmt = S.showMgmt && !!d.mgmt;   // only managed gear carries one
    out.push(GLYPH[d.kind](gx, cy - (hasMgmt ? 6 : 0), 15, S.chipStroke ?? kc, "none", 1.4));
    const ty = hasMgmt ? cy - 4 : cy + 1;
    out.push(`<text x="${(gx + 15).toFixed(1)}" y="${ty.toFixed(1)}" font-size="11.5" fill="${S.text}" font-weight="600" dominant-baseline="middle">${esc(d.label)}</text>`);
    if (hasMgmt) out.push(`<text x="${(gx + 15).toFixed(1)}" y="${(cy + 10).toFixed(1)}" font-size="9" fill="${S.sub}" font-family="${S.mono}">${esc(d.mgmt )}</text>`);
  }

  // legend (speeds actually present)
  const present = SPEED_ORDER.filter((s) => m.links.some((l) => l.speed === s) || (s === "LAG" && m.links.some((l) => l.bond)));
  let lx = 110; const ly = H - 35;
  out.push(`<text x="${lx}" y="${ly}" font-size="11" fill="${S.sub}" font-weight="700" font-family="${S.mono}">LINK SPEED</text>`);
  let x = lx + 92;
  for (const sp of present) {
    const c = S.speedColor[sp];
    out.push(`<line x1="${x}" y1="${ly - 3}" x2="${x + 24}" y2="${ly - 3}" stroke="${c}" stroke-width="3.2" stroke-linecap="round"/>`);
    out.push(`<text x="${x + 30}" y="${ly}" font-size="10.5" fill="${S.sub}" font-family="${S.mono}">${sp}</text>`);
    x += 92;
  }

  if (S.titleBlock) {
    const nodes = m.devices.length, links = m.links.length;
    out.push(`<rect x="${W - 252}" y="${H - 70}" width="236" height="54" fill="none" stroke="${S.cardStroke}" stroke-width="1.1"/>`);
    out.push(`<line x1="${W - 252}" y1="${H - 50}" x2="${W - 16}" y2="${H - 50}" stroke="${S.cardStroke}" stroke-width="1.1"/>`);
    out.push(`<text x="${W - 244}" y="${H - 55}" font-size="9.5" fill="${S.sub}" font-family="${S.mono}" letter-spacing="1">${esc(m.title.toUpperCase())} · PHYSICAL L1</text>`);
    out.push(`<text x="${W - 244}" y="${H - 34}" font-size="9" fill="${S.sub}" font-family="${S.mono}">${nodes} NODES · ${links} LINKS · REV A · NTS</text>`);
  }

  out.push("</svg>");
  return out.join("\n");
}



globalThis.NetScript = { parseNet, renderModel, resolveTheme, THEMES, clean, blueprint };
})();
