/**
 * Build the browser bundle for the live editor with zero external deps —
 * just Node 24's built-in TypeScript type-stripping.
 *
 * Concatenates the pure modules (no node: imports) in dependency order,
 * strips types + local import/export plumbing, and wraps them in an IIFE that
 * exposes `globalThis.NetScript`. Output: editor/netscript.js (committed, so
 * the static page works with no build step).
 *
 *   node scripts/build-editor.mjs
 */
import { stripTypeScriptTypes } from "node:module";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

const ORDER = ["model", "themes", "glyphs", "layout", "router", "parser", "render"];

function load(name) {
  let js = stripTypeScriptTypes(readFileSync(`src/${name}.ts`, "utf8"), { mode: "strip" });
  js = js.split("\n")
    .filter((l) => !/^\s*import\s/.test(l))                         // drop all imports
    .filter((l) => !/^\s*export\s*\{/.test(l))                      // drop bare re-exports
    .filter((l) => !/^\s*export\s+(type|interface)\b/.test(l))      // drop leftover type exports
    .join("\n")
    .replace(/^\s*export\s+(?=(const|function|class|let|var)\b)/gm, ""); // unwrap `export const/function`
  return `// ---- ${name}.ts ----\n${js}\n`;
}

let body = ORDER.map(load).join("\n");
// render.ts imports `escapeXml as esc` — re-bind it once in the shared scope.
body = body.replace("// ---- themes.ts ----", "const esc = escapeXml;\n\n// ---- themes.ts ----");

const out = `/* NetScript browser bundle — generated by scripts/build-editor.mjs. Do not edit by hand. */
(function () {
"use strict";

${body}

globalThis.NetScript = { parseNet, renderModel, resolveTheme, THEMES, clean, blueprint };
})();
`;

mkdirSync("editor", { recursive: true });
writeFileSync("editor/netscript.js", out);
console.log(`editor/netscript.js — ${out.length} bytes`);
