/**
 * Build the browser bundle for the live editor with zero external deps —
 * just Node 24's built-in TypeScript type-stripping.
 *
 * Concatenates the pure modules (no node: imports) in dependency order,
 * strips types + local import/export plumbing, and wraps them in an IIFE that
 * exposes `globalThis.NetScript`. Output: editor/netscript.js (committed, so
 * the static page works with no build step).
 *
 *   node scripts/build-editor.mjs
 */
import { stripTypeScriptTypes } from "node:module";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

// Dependency order — concatenation means a module must appear after anything
// it references at evaluation time (`const` does not hoist). Keep this in sync
// with the `from "./x.ts"` lines of whatever is listed; a missing entry does not
// fail the build, it produces a bundle that throws only on the code path that
// happens to touch the absent symbol.
const ORDER = [
  "model", "themes", "glyphs", "logical", "layout", "router", "tube",
  "traffic", "iso", "parser", "serialize", "render", "views",
];

/** True when a line closes an import — i.e. carries the `from "..."` source. */
const endsImport = (l) => /from\s*["'][^"']+["']\s*;?\s*$/.test(l) || /^\s*import\s*["'][^"']+["']\s*;?\s*$/.test(l);

/**
 * Drop local import/export plumbing.
 *
 * Imports are removed with a small state machine, not a per-line filter: a
 * multi-line `import {\n  a, b,\n} from "./x.ts";` would otherwise lose only
 * its first line and leave the members and the closing `} from "..."` behind
 * as stray syntax. That yields a bundle which fails to parse at all, from a
 * build that cheerfully reports success.
 */
function stripModuleSyntax(js) {
  const out = [];
  let inImport = false;
  for (const line of js.split("\n")) {
    if (inImport) { if (endsImport(line)) inImport = false; continue; }
    if (/^\s*import\s/.test(line)) { if (!endsImport(line)) inImport = true; continue; }
    if (/^\s*export\s*\{/.test(line)) continue;                     // bare re-export
    if (/^\s*export\s+(type|interface)\b/.test(line)) continue;     // leftover type export
    out.push(line);
  }
  return out.join("\n")
    .replace(/^\s*export\s+(?=(const|function|class|let|var)\b)/gm, ""); // unwrap `export const/function`
}

function load(name) {
  const js = stripModuleSyntax(stripTypeScriptTypes(readFileSync(`src/${name}.ts`, "utf8"), { mode: "strip" }));
  return `// ---- ${name}.ts ----\n${js}\n`;
}

let body = ORDER.map(load).join("\n");
// render.ts imports `escapeXml as esc` — re-bind it once in the shared scope.
body = body.replace("// ---- themes.ts ----", "const esc = escapeXml;\n\n// ---- themes.ts ----");

const out = `/* NetScript browser bundle — generated by scripts/build-editor.mjs. Do not edit by hand. */
(function () {
"use strict";

${body}

globalThis.NetScript = {
  parseNet, serializeNet,
  renderModel, renderModelIso, renderModelTraffic, renderTrafficIso, renderView,
  resolveTheme, THEMES, clean, blueprint,
};
})();
`;

mkdirSync("editor", { recursive: true });
writeFileSync("editor/netscript.js", out);
console.log(`editor/netscript.js — ${out.length} bytes`);
